// <auto-generated />
namespace CodeThoughts.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208032257158_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1aX2/bNhB/H7DvIOhpG9AoyYCiDZwWqZNsRZs/iL2+Box0tolRpCZSgf3Z9rCPtK+wo/6ZEilbdmI3K/oSWCTveLz73fH0U/79+5/B+3nMvEdIJRX81D86OPQ94KGIKJ+e+pmavHrjv3/34w+Diyiee1+qdcd6HUpyeerPlEpOgkCGM4iJPIhpmAopJuogFHFAIhEcHx6+CY4OA0AVPuryvMFdxhWNIX/Ax6HgISQqI+xKRMBkOY4zo1yrd01ikAkJ4dQf4orxTGTTmZIH50QR3ztjlKAhI2CTDa06fKut8uv9cMcLtEwtxosE8l1P/Q9MTM0VuOYTLBoDOHSbigRStbiDSSn3MfK9oCkXtAVrMUNGb42/uPr12PeuM8bIA8OBCWESfC95fTJSIoXfgENKFES3RClIuZaF3PTSBSfJ635eeBscHmsvBIRzoYjCAFuGt8zUfytDRypFrPjeJZ1D9Bn4VM1qY6/IvBrBn773B6cILRRSaQbm4Yrn1qbX5JFOc3ta298KqaTv3QHLZ+WMJkX0D/TMfR4w7zIV8Z1g5fJ88H5M0ikotFy0Z0YiS8OWCYNgiYWVCNFqviOkYeaYKrYHiLR2xXIAwxT0oau99dCYxuBw1GpdWJMUumvvZyj3/X189Xnve+tUWA+wvmla5OHmWVrlop2lVf72tWAo4hh96a4V5eR9nr2GIea4VTEak08qGqWm73Xjm8tgjY3ny6ICntvit51LTnD3we+ZlCKkuQ2GYfeO5uiCR15nSheRqIoAOj5jiiaMhrjlqf+L5RaXsjonl8qKYtJUduS3M+mGnwMDBd5ZqPI2dkhkSCI7GOiDqDmCyQepzgLCEFZSpYRyZWcq5SFNCOsyuSXQM7m1QbXq9sw5JMB1fnb5vM+eVd23963Vtxy0zh+DwADMahw1cNwVfTeolwCoqukGgHLX+dUA/fqYclm9B1i5/N9n26oW7gFZRd3SRR8lIDWgnV8E"
                       + "cxtcev0IlLESO4Vl+WvUFgtGTeHylcQSLkC0RnjZpljyNa5bKgwfNI0o+ypj3mq62qFYVbBrU+sjWpFcVaIN8dK97axoHqTHIZvXnn3O7nKyvqAY5i5jsuLAzhKyzmUrzlxdvjWIl0RIUDAhFWMSdFAmgyuSJNjmGBRKOeKNSv7k1WhzkiQudAShdHAltbX1TthGkim0Zgvq5pKmUmna5oHoLmgYxdayHilb7WRmrh2mKpeq1fp3BaIWiXTgyoyl8y7xPDrS+dGghWpbLCeuCCOpowkfCpbFvLsod0sXrIspX4zYGgZBy26r+lrOsS6rpqd7xaGA+9Pi4ErbHnFwi+0mDiW3YSooh/rraLznmJoaE/311e86pq56cGM9Bfvg0FVM9NdXdZamqq5u86vhtq71T4Ou840+17MOvZ2SuwHwSwVf1SyaaroayB2DxbqJ20vq3esbuXXzDspbsN8Xjca1WCzxPXTPI430lThaSAVxAbPRX2zIaO7aasEV4XQCUo3Fn6C/zuCtvf1XkZq1kTJiL/HTCNVHX0tVbUgWmZ80+CNJwxlJf4rJ/OfV7M8L/0awE1c1uP0NfNWL7YvwQT0D2/ckuxwc/JP0NXn1PCgrT/fySeSdAOulwqFJ6G4fvm041OJ1fp9UZ/N9fgvOditeq+P9ayf86DfCifYKz46gUfNS23CwW5Ppe2Q6/x/sps2orOc4OynOou3EmvsgMK5FdXOzdi72s5P8dKl1E2MdvOgqWtSlvIu62xFpavp0yQmt40ktnvDlUKO9zHNXA8c77U7YT/vdClPL+J8yzGpJp0sV+j/MOISNpKrXfOQTUeV2y6JqSashuAJFsDMhZ6miExIqnA5Byvzz8hfCMlxyET9A9JHfZCrJFB4Z4ge2MJ2ha8Sq/XOKt2nz4CbJvwE/xxHQTKqbqxv+IaMsqu2+dLQzHSp08Sm7Px1LpbvA6aLWdC14T0Wl++qaOYY4YahM3vAReYRu29b7sOmx"
                       + "wTkl05TEstSxlMdHhF8Uz9/9Bxmop5UVKQAA"; }
        }
    }
}
