// <auto-generated />
namespace CodeThoughts.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddedUrlcolumn : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201209171120383_Added Url column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1a227jNhB9L9B/EPTUFtjISYHFbmDvInGSdrGbC2Lvvga0NLaJUqQqUoH9bX3oJ/UXSupmSqRk+Zq02JfAIjnD4cyZ0egw//z1d//jIiTOM8QcMzpwT096rgPUZwGms4GbiOmbd+7HDz/+0L8OwoXzrVh3ptZJScoH7lyI6NzzuD+HEPGTEPsx42wqTnwWeihg3lmv98477XkgVbhSl+P0HxMqcAjpg3wcMupDJBJEblkAhOfjcmaUanXuUAg8Qj4M3KFcMZ6zZDYX/OQKCeQ6FwQjacgIyHRDq3rvlVVuuZ/c8VpaJpbjZQTprgP3krCZvkKu+QzLyoAceohZBLFYPsI0l/sUuI5XlfPqgqWYJqO2lr+o+PXMde4SQtCEyIEpIhxcJ3p7PhIsht+AQowEBA9ICIipkoXU9NwF59Hbbl547/XOlBc8RCkTSMgAG4bXzFR/C0NHIpZYcZ0bvIDgC9CZmJfG3qJFMSJ/us5XiiW0pJCIE9APlz3XNr1Dz3iW2lPb/oFxwV3nEUg6y+c4yqJ/omae0oA5NzELHxnJl6eDT2MUz0BIy1l9ZsSS2K+Z0PdWWGhFiFLzHSEVM8dYkCNApLbr15gcfU9ZgmAYg3J0sbcaGuMQLMFp1/WQTAjm85WmSyZxiujGimRBFTLWR3dGvu/v49svR99b5fH67OhaY7IisnmJKQqJWWKK4tPVgiELQ+lLe6HLJ5/S0qMZoo8b5a4yuVPFyzV9L3oHKwUvlcEKG/vLogye2+K3nktWcHfB7wXnzMepDZphT5bO7poGTmNKZ5EoioB0fEIEjgj25ZYD9xfDLTZlZU6ulGXFpKrs1K1n0j29AgICnAtfpD34EHEfBWYwpA+C6ohMPohVFiAiYcVFjDAVZqZi6uMIkSaTawIdk1sZVKquz1xBBFTlZ5PPu+xZ1H1z31J9zUHr/NH3NMC046iC46bo20G9AkBRTTcAlL3OtwP05TFls/oI"
                       + "sLL5v8u2RS08ArKyuqWKvpSAWIN2+iJYmOBS60cgtJWyU1iVv0ptMWBUFc6/pwzhDERrhFdtiiFf4rqmQvNB1Yi8r9LmjaarHoq2gl2aWh7RiGRbidbEc/fWs6J6kA6HrL72zHM2l5P1BUUzdxWTlgNbS8g6l7WcuXj5liBesTheRuMUdI/XwPf0b1EUyTZH43/yEWeUkz9vRpszPGGmw/O5hegprS13km0kmkFtNuOdbnDMheKcJkh1QcMgNJZ1SNliJz1zzTAVuVSsVr8LENUYsBNbZqycdyPPoyKdHg1qqDbFUtYNERRbmvAhI0lIm4tys3RGGeny2Yipoe/V7Daqr+Ec42VV9XSnOGRw3y0OtrTtEAe72GHikBMzuoJ8qLuOlGbRNaQD3eUr30m6nspEd30abaJr04a76yq/u3RN5eDGejImxKIrm+iur+hydVVNne+L5VD53tktjazsQqpnXSY1Sh4mmfYN5H2Br2hcK9nQ0MweGCxGV1BfUu5edge1LqCfv5G7XQ1VXtHZEteR7nnGgXo9j5ZcQJjBbPQnGRKcurZYcIsongIXY/YHqGsu2UFsf71UMkicB+Q13jFhdfS1tNmGxJV+N0SfUezPUfxTiBY/tzNRr/yy5SCuqlySbOCr1ouPnfRYGMxAPoi9XGZMsNiVBt3pcJbLiZ30VS8cUoS0nu71s+sHQfk+MbVPOFSZ7u3Dtw25nPEcx+SAq0THFmT2VoRfw4fpQYjj/wlZ3Ck8B4JGSdhtQ05vfctwRAr4v0H7mlTTevK3kfvNemBZcydMxjWrbnY600YLN7LCNrV2xrCBMG7ji23KmzjNA7HJuk9XZNk6AtkgUF8PZ9zJPHs1sHxgH4QWNj/0ZGpp/ykos5rj2UqF+r9BCn4lqco1n+iUFblds6hYUmsIbkEg2Zmgi1jgKfKFnPaB8/Te/RsiiVxyHU4g+ETvExElQh4ZwglZ6s5QNaJt/5T7rtrcv4/Sy/F9HEGa"
                       + "iVVzdU8vE0yC0u4bSzvToEIVn7z7U7EUqgucLUtNd4x2VJS7r6yZYwgjIpXxezpCz9Bs23ofVj3Wv8JoFqOQ5zpW8vJRwi8IFx/+BRgz+/nrKgAA"; }
        }
    }
}
