// <auto-generated />
namespace CodeThoughts.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddPublishedflag : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201209121853200_Add Published flag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1azW7jNhC+F+g7CDq1BdZyUmCxG9i7SJykDbpOgtjda0BLY5soRaoiFdjP1kMfqa9QUn+mRMqWf5MWewkskjMcznwzHH3KP3/93fu8CInzAjHHjPbds07XdYD6LMB01ncTMX33wf386fvvejdBuHC+FuvO1TopSXnfnQsRXXge9+cQIt4JsR8zzqai47PQQwHzzrvdD95Z1wOpwpW6HKf3lFCBQ0gf5OOAUR8ikSAyZAEQno/LmVGq1blHIfAI+dB3B3LFeM6S2VzwzjUSyHUuCUbSkBGQ6ZZWdT8qq9xyP7njjbRMLMfLCNJd++4VYTN9hVzzGywrA3LoMWYRxGL5BNNc7i5wHa8q59UFSzFNRm0tf1Hx87nr3CeEoAmRA1NEOLhO9P5iJFgMvwCFGAkIHpEQEFMlC6npuQsuovftvPDR654rL3iIUiaQkAE2DK+Zqf4Who5ELLHiOrd4AcEXoDMxL40dokUxIn+6zu8US2hJIREnoB8ue65teo9e8Cy1p7b9I+OCu84TkHSWz3GURb+jZp7TgDm3MQufGMmXp4PPYxTPQEjLWX1mxJLYr5nQ81ZYWIsQpeYbQipmjrEgJ4BIbVdZDmAQgzp0sbcaGuMQLI5ar+sxmRDM5ytNV0xiBtGtFcniJqTfT+6MfN9fx8MvJ99b5dRmpLbN9yyht0/3IqnNdC8KQVsLBiwMpS/tRSeffE7LgGaIPm6UnsrkXtUn1/StAB2tFLxWBitsHC6LMnjuit96LlnB3Qa/l5wzH6c2aIY9W7qsGxo4jSmdRaIoAtLxCRE4ItiXW/bdnwy32JSVOblSlhWTqrIzt55JD/QaCAhwLn2R9sMDxH0UmMGQPgiqIzL5IFZZgIiEFRcxwlSYmYqpjyNEmkyuCbRMbmVQqbo+cw0RUJWfTT5vs2dR9819S/U1B23yR8/TALMeRxUcN0XfDuoVAIpqugWg7HV+PUBfH1M2q08AK5v/22xb"
                       + "1MITICurW6roSwmINWinF8HCBJdaPwKhrZSdwqr8VWqLAaOqcP5uYwhnINogvGpTDPkS1zUVmg+qRuR9lTZvNF31UKwr2KWp5RGNSK4r0Zp47t56VlQP0uKQ1WvPPGdzOdlcUDRzVzFZc2BrCdnksjVnLi7fEsQrRsXLKJWCevEauJfeEEWRbHM0LiYfcUY5EfNutD3bEmY6PJ9bSJfS2nIn2UaiGdRmMw7oFsdcKP5nglQXNAhCY1mLlC120jPXDFORS8Vq9bsAUY2N6tgyY+W8W3keFen0aFBDtSmWMmCIoNjShA8YSULaXJSbpTP6RpfPRkwNPa9mt1F9DecYl1XV063ikMF9vzjY0rZFHOxix4lDTpLoCvKh9joq7zm6pspEe30a7aFr04bb6yrfm3RN5eDWejImw6Irm2ivr+hSdVVNneur5UB5b+yXBlZ2INWzKRMaJY+TDIcG8qHAVzSelWxoaEaPDBbjVq8vKXcvb/faLd7Lb9R2n1kqV2y2xHWke15woK7X0ZILCDOYjf4kA4JT1xYLhojiKXAxZn+A+mQkO4DdP9WUDBDnAXmL32uwOvpG2mtL4kn/zkJfUOzPUfxDiBY/rmeS3viHi6O4qvLBYQtftWIOA/kgDvIRYYLFvvTjXoezfBTYS1+V6E8ju/Z0b5/VPgo6D4mpQ8KhyjDvHr5dSN2MXzgl91olGHYgkXci2hpeCI9C2P5PSNpW4TkSNEqibBdSeGd2/4TU63+DbjUpns2kayPnmvWusuZOmIxrVt3sNKKNjm1kY21q7UxdA1G7jqe1KW/iEo/E4uo+XZFUm4hbg7h8O1xtK/Ps1cDyYnwUOtZ8QZOppf23nMxqjmcrFep/5yj4laQq19zRKStyu2ZRsaTWEAxBINmZoMtY4CnyhZz2gfP0e/dXRBK55CacQHBHHxIRJUIeGcIJWerOUDVi3f4p51y1ufcQpR+lD3EEaSZWzdUDvUowCUq7by3tTIMKVXzy"
                       + "7k/FUqgucLYsNd0z2lJR7r6yZo4hjIhUxh/oCL1As22bfVj1WO8ao1mMQp7rWMnLRwm/IFx8+hfV94bW7ykAAA=="; }
        }
    }
}
